# Generated by Django 3.2.23 on 2024-01-19 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisator', '0002_auto_20240118_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisateur',
            name='organisation',
        ),
        migrations.AddField(
            model_name='organisateur',
            name='organisations_affiliees',
            field=models.ManyToManyField(related_name='organisateurs_affiliees', to='organisator.Organisation'),
        ),
        migrations.AddField(
            model_name='organisateur',
            name='organisations_crees',
            field=models.ManyToManyField(related_name='organisateurs', to='organisator.Organisation'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
