# Generated by Django 3.2.23 on 2024-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisator', '0003_auto_20240119_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisateur',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
