# Generated by Django 3.2.23 on 2024-02-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisator', '0004_organisateur_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images')),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('confirmé', 'Confirmé'), ('annuler', 'Annuler'), ('en_cours', 'En cours'), ('termine', 'Terminé')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.categorie')),
                ('organisator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisator.organisation')),
            ],
        ),
    ]
