# Generated by Django 3.2.23 on 2024-02-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0002_favoris'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['name'], 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_datetime'], 'verbose_name_plural': 'Evenements'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='evenement.categorie'),
        ),
    ]
