# Generated by Django 3.2.23 on 2024-02-26 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evenement', '0003_auto_20240224_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='evenement.event'),
        ),
        migrations.AlterUniqueTogether(
            name='favoris',
            unique_together={('user', 'event')},
        ),
    ]
