# Generated by Django 3.2.23 on 2024-02-27 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0004_auto_20240226_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoris',
            options={'ordering': ['-add_time']},
        ),
        migrations.AddField(
            model_name='favoris',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
